const valid_courses = [
  "N/A",
  "Associate Degree Associate in Tourism Management (ATM) Associate in Tourism Management (ATM)",
  "Bachelor in Advertising and Public Relations (BADPR)",
  "Bachelor in Cooperatives (BCOOP)",
  "Bachelor in Elementary Education (BEED)",
  "Bachelor in Secondary Education major in Mathematics (BSEDMT)",
  "Bachelor of Arts in Broadcasting (BA Broadcasting)",
  "Bachelor of Arts in Communication Research (BACR)",
  "Bachelor of Arts in English Language Studies (formerly Bachelor of Arts in English) (ABELS)",
  "Bachelor of Arts in Filipinology (ABF)",
  "Bachelor of Arts in History (BAH)",
  "Bachelor of Arts in International Studies (BAIS)",
  "Bachelor of Arts in Journalism (BAJ)",
  "Bachelor of Arts in Literary and Cultural Studies (ABLCS)",
  "Bachelor of Arts in Philosophy (AB-PHILO)",
  "Bachelor of Arts in Political Economy (BAPE)",
  "Bachelor of Arts in Political Science (BAPS)",
  "Bachelor of Arts in Sociology (formerly Bachelor of Science in Sociology) (BAS)",
  "Bachelor of Business Technology and Livelihood Education (BBTLE)",
  "Bachelor of Business Technology and Livelihood Education major in Home Economics (BBTLEDHE)",
  "Bachelor of Early Childhood Education (BECEd)",
  "Bachelor of Elementary Education (BEEd)",
  "Bachelor of Library and Information Science (BLIS)",
  "Bachelor of Performing Arts major in Theater Arts (formerly BA Theater Arts) (BPEA)",
  "Bachelor of Physical Education (BPE)",
  "Bachelor of Public Administration (BPA)",
  "Bachelor of Public Administration major in Public Financial Management (BPAPFM)",
  "Bachelor of Science Food Technology (BSFT)",
  "Bachelor of Science in Accountancy (BSA)",
  "Bachelor of Science in Agricultural Business Management (BSAM)",
  "Bachelor of Science in Applied Mathematics (BSAPMATH)",
  "Bachelor of Science in Architecture (BS-ARCH)",
  "Bachelor of Science in Biology (BSBIO)",
  "Bachelor of Science in Business Administration Major in Financial Management (BSBAFM)",
  "Bachelor of Science in Business Administration major in Human Resource Management (BSBA-HRM)",
  "Bachelor of Science in Business Administration major in Marketing Management (BSBA-MM)",
  "Bachelor of Science in Chemistry (BSCHEM)",
  "Bachelor of Science in Civil Engineering (BSCE)",
  "Bachelor of Science in Computer Engineering (BSCpE)",
  "Bachelor of Science in Computer Science (BSCS)",
  "Bachelor of Science in Cooperatives (formerly Bachelor in Cooperatives) (BSC)",
  "Bachelor of Science in Economics (BSE)",
  "Bachelor of Science in Electrical Engineering (BSEE)",
  "Bachelor of Science in Electronics Engineering (BS-ECE)",
  "Bachelor of Science in Entrepreneurship (BSENTREP)",
  "Bachelor of Science in Entrepreneurship (Open University) (BSENTREP)",
  "Bachelor of Science in Environmental Planning (BSEP)",
  "Bachelor of Science in Exercises and Sports (BSESS)",
  "Bachelor of Science in Hospitality Management (BSHM)",
  "Bachelor of Science in Industrial Engineering (BSIE)",
  "Bachelor of Science in Information Technology (BSIT)",
  "Bachelor of Science in Interior Design (BSID)",
  "Bachelor of Science in Management Accounting (BSMA)",
  "Bachelor of Science in Mathematics (BSMATH)",
  "Bachelor of Science in Mechanical Engineering (BSME)",
  "Bachelor of Science in Nutrition and Dietetics (BSND)",
  "Bachelor of Science in Office Administration (BSOA)",
  "Bachelor of Science in Office Administration major in Legal Transcription (BSOALT)",
  "Bachelor of Science in Physics (BSPHY)",
  "Bachelor of Science in Psychology (BSPSY)",
  "Bachelor of Science in Railway Engineering (formerly Bachelor of Science in Railway Engineering and Management) (BSRE)",
  "Bachelor of Science in Statistics (formerly Bachelor in Applied Statistics) (BSSTAT)",
  "Bachelor of Science in Tourism Management (BSTM)",
  "Bachelor of Science in Transportation Management (formerly Bachelor in Transportation Management) (BSTRM)",
  "Bachelor of Secondary Education (BSEd) major in:",
  "Bachelor of Secondary Education major in English (BSEDEN)",
  "Bachelor of Secondary Education major in Filipino (BSEDFL)",
  "Bachelor of Secondary Education major in Mathematics (BSEDMT)",
  "Bachelor of Secondary Education major in Social Studies (BSEDSS)",
  "Bachelor of Technology and Livelihood Education (BTLEd) major in:",
  "Diploma in Computer Engineering Technology (DCET)",
  "Diploma in Electrical Engineering Technology (DEET)",
  "Diploma in Electronics Engineering Technology (DECET)",
  "Diploma in Information Communication Technology (DICT)",
  "Diploma in Mechanical Engineering Technology (DMET)",
  "Diploma in Office Management Technology (DOMT)",
  "Diploma in Office Management Technology Legal Office Management (DOMTLOM)",
  "Diploma in Office Management Technology Medical Office Management (DOMTMOM)",
  "Doctor in Business Administration (DBA)",
  "Doctor in Engineering Management (D.Eng)",
  "Doctor in Public Administration (DPA)",
  "Doctor of Philosophy in Communication (PhD Com)",
  "Doctor of Philosophy in Economics (PhD Econ)",
  "Doctor of Philosophy in English Language Studies (PhD ELS)",
  "Doctor of Philosophy in Filipino (PhD Fil)",
  "Doctor of Philosophy in Psychology (PhD Psy)",
  "Doctor of Philsophy in Education Management (PhDEM)",
  "Juris Doctor (JD)",
  "Master in Applied Statistics (MAS)",
  "Master in Business Administration (MBA)",
  "Master in Business Education (MBE)",
  "Master in Communication (MC)",
  "Master in Educational Management (MEM, Open University System)",
  "Master in Information Technology (MIT)",
  "Master in Library and Information Science (MLIS)",
  "Master in Public Administration (MPA, Open University System)",
  "Master in Public Administration (MPA)",
  "Master of Arts in Communication (MAC)",
  "Master of Arts in Education major in Mathematics Education (MAEd-ME)",
  "Master of Arts in Education major in Teaching in the Challenged Areas (MAED-TCA)",
  "Master of Arts in Education Management  (MAEM)",
  "Master of Arts in Education Management (Open University)",
  "Master of Arts in English Language Studies (MAELS)",
  "Master of Arts in English Language Teaching (MAELT)",
  "Master of Arts in Filipino (MAF)",
  "Master of Arts in Philippine Studies (MAPhilS)",
  "Master of Arts in Philosophy (MAPhilo)",
  "Master of Arts in Physical Education and Sports (MAPES)",
  "Master of Arts in Psychology (MAP)",
  "Master of Arts in Sociology (MASocio)",
  "Master of Science in Biology (MSBio)",
  "Master of Science in Civil Engineering (MSCE)",
  "Master of Science in Computer Engineering (MSCpE)",
  "Master of Science in Construction Management (MSCM)",
  "Master of Science in Economics (MSEcon)",
  "Master of Science in Electronics Engineering (MSEcE)",
  "Master of Science in Industrial Engineering (MSIE)",
  "Master of Science in Information Technology (MSIT)",
  "Master of Science in International Tourism and Hospitality Management (MSITHM)",
  "Master of Science in Mathematics (MSMath)",
  "Master of Science in Mechanical Engineering (MSME)",
  "Master of Science in Nutrition and Dietetics (MSND)",
  "Masters in Educational Management (MEM, Open University System)",
  "Masters in Public Administration (MPA, Open University System)",
  "Post Baccalaureate Diploma in Information Technology (PBDIT)",
  "Post Baccalaureate in Teacher Education (PBTE)",
  "Post-Baccalaureate Diploma in Education (PBDE)",
  "Professional Science Masters in Railway Engineering Management (PSMREM)",
];

export default valid_courses;
